name: Build Anki decks and upload artifacts

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        language:
          - rust
          - godot
          - wolfram-language
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-23.11
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Nix Flake
        run: nix flake check

      - name: Build Anki deck with Nix
        run: |
          nix develop --command bash -c \
            'cd ${{ matrix.language }} && make cards.apkg'

      - name: Rename artifact
        run: cp ${{ matrix.language }}/cards.apkg cards-${{ matrix.language }}.apkg

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cards-${{ matrix.language }}.apkg
